### ISSUE TITLE
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vowave** [chrisweb/waveform-data-generator#2]
Hello 
Sorry is there a permanent fix for this error ?

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

    4839 ms: Scavenge 1336.3 (1344.7) -> 1334.4 (1344.7) MB, 1.3 / 0.0 ms (+ 2.4 ms in 32 steps since last GC) [allocation failure].
    5103 ms: Scavenge 1336.3 (1344.7) -> 1334.4 (1344.7) MB, 1.3 / 0.0 ms (+ 1.4 ms in 31 steps since last GC) [allocation failure].
    5451 ms: Scavenge 1336.3 (1344.7) -> 1334.4 (1344.7) MB, 1.9 / 0.0 ms (+ 49.9 ms in 60 steps since last GC) [allocation failure].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2407d04cf781 <JS Object>
    2: /* anonymous */ [/home/vowave/public_html/nodejs/waveform/server/library/audioDataAnalyzer.js:~284] [pc=0x3ae91a4a2bb6] (this=0x37a8febe031 <a Socket with map 0x2b64bad34b91>,buffer=0x257c15eaae81 <an Uint8Array with map 0x2b64bad34be9>)
    3: emit [events.js:~136] [pc=0x3ae91a4b49be] (this=0x37a8febe031 <a Socket with map 0x2b64bad34b91>,type=0x2407d04dd189 <String[4]: data>)
    4: ar...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x710f4c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Heap::AllocateRawFixedArray(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Heap::AllocateUninitializedFixedArray(int) [node]
 7: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 8: 0xa7d60f [node]
 9: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
10: 0x3ae91a3079a7

**Comment by chrisweb** [comment]
I haven't touched this project for a while, I need to investigate, never had this error, lets see if I can reproduce it, can tell when I will have time though

**Comment by peet-j** [comment]
I just got the same error. Node v11.0
Input file is around 75MB
```
waveform-data-generator (master *%)$ node --max-old-space-size=4096 cli ./downloads 11d5691c-97dc-4731-a8ad-dddde941df28 mp3 200 local json false

<--- Last few GCs --->

[12594:0x104000c00]     4904 ms: Scavenge 1219.2 (1226.6) -> 1215.3 (1226.6) MB, 12.2 / 0.0 ms  (average mu = 0.967, current mu = 0.994) allocation failure
[12594:0x104000c00]     6826 ms: Scavenge 2079.9 (2087.3) -> 2076.0 (2087.3) MB, 22.2 / 0.0 ms  (average mu = 0.967, current mu = 0.994) allocation failure
[12594:0x104000c00]     7697 ms: Scavenge 2079.9 (2087.3) -> 2076.0 (2087.3) MB, 20.2 / 0.0 ms  (average mu = 0.967, current mu = 0.994) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3b2e36fcfb7d]
Security context: 0x2de20ff9d969 <JSObject>
    1: /* anonymous */ [0x2de2e927aa21] [/Users/code/global/waveform-data-generator/server/library/audioDataAnalyzer.js:~283] [pc=0x3b2e3706e3b9](this=0x2de2e9279ae1 <Socket map = 0x2de2afe53601>,0x2de298ca7401 <Uint8Array map = 0x2de2afe544b1>)
    2: emit [0x2de20ffc36f9] [events.js:~140] [pc=0x3b2e37071ab1](this=0x2de2e9279ae1 <Socket map = 0x2...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x10003a9d9 node::Abort() [/Users/.nvm/versions/node/v11.0.0/bin/node]
 2: 0x10003abe4 node::FatalTryCatch::~FatalTryCatch() [/Users/.nvm/versions/node/v11.0.0/bin/node]
 3: 0x10019ed17 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 4: 0x10019ecb4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 5: 0x1005a5882 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 6: 0x10057d39a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 7: 0x10051b4e4 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedSmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)0> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 8: 0x1007fec82 v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/.nvm/versions/node/v11.0.0/bin/node]
 9: 0x3b2e36fcfb7d
10: 0x3b2e3706e3b9
Abort trap: 6
```

**Comment by peet-j** [comment]
ok, using `sr=22050` prevents this

**Comment by chrisweb** [comment]
Yes @peet-j is right, it's actually already a tip in the README, when you run out of memory, you need to reduce the amount of samples the tool will read by using the sr parameter

by default it is 44100 which is already a lot higher than what you will ever need to make a graphically beautiful waveform, so lowering it to 22050 will still produce a nice waveform but also lower the memory consumption

so this command should do the trick:
`node cli ./downloads MY_AUDIO_FILE ogg 200 local json sr=22050`
